# Generated by Django 4.2.13 on 2024-06-10 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='Фото')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('disease', models.CharField(blank=True, max_length=150, null=True, verbose_name='Болезнь')),
                ('doctor', models.CharField(blank=True, max_length=150, null=True, verbose_name='Доктор')),
                ('education', models.CharField(blank=True, max_length=200, null=True, verbose_name='Образование')),
                ('work', models.CharField(blank=True, max_length=500, null=True, verbose_name='Работа')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Информация')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
            },
        ),
    ]
