# Generated by Django 4.2.13 on 2024-06-19 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_doctor_profile_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctordirection',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direction', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='doctorinfo',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='api.doctor'),
        ),
    ]
