# Generated by Django 4.2.13 on 2024-06-27 16:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_doctordirection_doctor_alter_doctorinfo_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Категория доктора')),
            ],
            options={
                'verbose_name': 'Категория доктора',
                'verbose_name_plural': 'Категории докторов',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c2aa765c-24bb-4c6e-bb52-54ded752c2c6')),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.doctorcategory', verbose_name='Доктор'),
        ),
    ]
