# Generated by Django 4.2.13 on 2024-06-27 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_doctorcategory_doctor_uuid_alter_doctor_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e84ddb27-bb49-476b-98c4-dd28a8a9855b')),
        ),
    ]
