# Generated by Django 4.2.13 on 2024-06-27 16:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_doctor_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.doctorcategory', verbose_name='Доктор'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b841ef65-ffdd-4e47-a277-2a6f8a5886fa')),
        ),
    ]
