# Generated by Django 4.2.13 on 2024-06-27 16:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_doctor_doctor_alter_doctor_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bb0050d4-6246-42a6-b0f7-52446bcf2061')),
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='symptoms/')),
                ('doctor', models.ManyToManyField(to='api.doctor', verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'Симптом',
                'verbose_name_plural': 'Симптомы',
            },
        ),
    ]
